apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-lauren-demo-instance
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: lauren-demo/environments/staging/lauren-demo
    repoURL: https://github.com/client-engineering-gitops-h/multi-tenancy-gitops-apps.git
    targetRevision: master
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
