apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-scc-lauren
  annotations:
    argocd.argoproj.io/sync-wave: "250"
  labels:
    gitops.tier.group: cntk
    gitops.tier.layer: applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ci
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: htz-int/environment/lauren/scc
    repoURL: https://github.com/client-engineering-gitops-htz/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true