apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-lauren-rest-ci
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ci
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: htz-int/environment/lauren/
    repoURL: https://github.com/client-engineering-gitops-htz/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true